### ISSUE TITLE
feat: sidebar 컴포넌트 구현

### ISSUE THREAD

**Issue by changhui-chan** [changhui-chan/10-Sprint-Fandom-K#13]
## To-Do
- [x] 디자인 설계
- [x] 구조 설계
- [x] 사이드바 링크 연결
- [x] 사용할 아이콘 이미지 추가
- [ ] css animation 혹은 transition
- [x] 통합 테스트 및 최종 merge
