### ISSUE TITLE
feat: header 컴포넌트 구현

### ISSUE THREAD

**Issue by changhui-chan** [changhui-chan/10-Sprint-Fandom-K#14]
## To-Do
- [ ] 사이드바 컴포넌트 구현
- [ ] 로고 이미지 링크 연결
- [ ] 크레딧 컴포넌트 구현
- [ ] 아바타 컴포넌트 구현
- [ ] 헤더에서 사용될 컴포넌트 연결
- [ ] 통합 테스트 및 최종 merge
