### ISSUE TITLE
feat: /mypage 페이지 구현

### ISSUE THREAD

**Issue by changhui-chan** [changhui-chan/10-Sprint-Fandom-K#15]
## To-Do
- [x] 아이돌 스크롤 기능 구현
- [x] 아이돌 컴포넌트 구현
- [x] 피그마 요구사항 진행
- [x] 통합 테스트 및 최종 merge
