### ISSUE TITLE
fix: 공용 모달 컴포넌트 수정

### ISSUE THREAD

**Issue by najitwo** [changhui-chan/10-Sprint-Fandom-K#42]
## To-Do
- [x] 모달 상태 변수를 메서드로 관리 할 수 있게 수정
- [x] 누락된 button props 추가
- [x] 모달 외부 여백 조정할 수 있게 사용자 정의 스타일 설정
- [x] 모달에 표시되는 데이터를 넣기 위한 상태 관리 변수 추가
